listener {
  timeout = 270
  on-timeout = notify-send "You are IDLE, sleeping in 30 seconds"
}

listener {
  timeout = 300
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' # shuts off monitors
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
