cursor            #d5c871
cursor_text_color #373100

foreground            #e7e2d5
background            #100e07
selection_foreground  #353117
selection_background  #cfc7a2
url_color             #cfc7a2

#: black 000000 767676
color0  #15130c
color8  #37352c
#: red cc0403 f2201f
color1  #f5df98
color9  #f3d780
#: green 19cb00 23fd00
color2  #cfc7a2
color10 #ebe3bd
#: yellow cecb00 fffd00
color3  #a7d0b7
color11 #c3ecd2
#: blue 0d73cc 1a8fff
color4  #504700
color12 #d5c871
#: magenta cb1ed1 fd28ff
color5  #4c472b
color13 #cfc7a2
#: cyan 0dcdcd 14ffff
color6  #294e3b
color14 #a7d0b7
#: white dddddd ffffff
color7  #ccc6b5
color15 #e7e2d5

mark1_foreground #201c00
mark1_background #f2e48a
mark2_foreground #1f1c05
mark2_background #ebe3bd
mark3_foreground #002112
mark3_background #c3ecd2

active_tab_foreground #373100
active_tab_background #d5c871
inactive_tab_foreground #f2e48a
inactive_tab_background #504700

active_border_color #d5c871
inactive_border_color #373100
# bell_border_color #ff5a00
visual_bell_color #574c26
